/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sogemee;

import approvisionnement.Fen_Approvisionnement;
import fabrication.Fen_Fabrication;
import gesperson.Fen_Menu_GesPersonnel;
import vente.Menu_Vente;

/**
 *
 * @author el-diablo
 */
public class Guide extends javax.swing.JFrame {

    private Fen_Fabrication f=new Fen_Fabrication();
    private Fen_Menu_GesPersonnel p=new Fen_Menu_GesPersonnel();
    private Menu_Vente v=new Menu_Vente();
    
    
    /**
     * Creates new form Guide
     */
    public Guide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setTitle("Guide ");
        setResizable(false);

        jButton1.setText("<html><font color=\"red\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ges<br> APPROVISIONNEMENT</font></html>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<html><font color=\"red\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ges<br> PERSONNEL</font></html>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("<html><font color=\"red\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ges<br>FABRICATION</font></html>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("<html><font color=\"red\">&nbsp;&nbsp;Ges<br> VENTE et COMPTABILITE</font></html>");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("<html><font color=\"red\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ges<br> UTILISATEURS</font></html>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jMenu1.setText("Fichier");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Aide");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(SOGEMEE.getLog().getPrinc().getPerson().isVisible()){
            SOGEMEE.getLog().getPrinc().getPerson().dispose();
        }
        if(SOGEMEE.getLog().getPrinc().getVente().isVisible()){
            SOGEMEE.getLog().getPrinc().getVente().dispose();
        }
         if(SOGEMEE.getLog().getPrinc().getFabrication().isVisible()){
            SOGEMEE.getLog().getPrinc().getFabrication().dispose();
        }
            if(SOGEMEE.getLog().getPrinc().getApprovisionnement().isVisible()){
            SOGEMEE.getLog().getPrinc().getApprovisionnement().dispose();
        }
        
        SOGEMEE.getLog().getPrinc().getApprovisionnement();
        SOGEMEE.getLog().getPrinc().getApprovisionnement().setVisible(true);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(SOGEMEE.getLog().getPrinc().getPerson().isVisible()){
            SOGEMEE.getLog().getPrinc().getPerson().dispose();
        }
        if(SOGEMEE.getLog().getPrinc().getVente().isVisible()){
            SOGEMEE.getLog().getPrinc().getVente().dispose();
        }
         if(SOGEMEE.getLog().getPrinc().getFabrication().isVisible()){
            SOGEMEE.getLog().getPrinc().getFabrication().dispose();
        }
            if(SOGEMEE.getLog().getPrinc().getApprovisionnement().isVisible()){
            SOGEMEE.getLog().getPrinc().getApprovisionnement().dispose();
        }
          
        SOGEMEE.getLog().getPrinc().getPerson();
        SOGEMEE.getLog().getPrinc().getPerson().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(SOGEMEE.getLog().getPrinc().getPerson().isVisible()){
            SOGEMEE.getLog().getPrinc().getPerson().dispose();
        }
        if(SOGEMEE.getLog().getPrinc().getVente().isVisible()){
            SOGEMEE.getLog().getPrinc().getVente().dispose();
        }
         if(SOGEMEE.getLog().getPrinc().getFabrication().isVisible()){
            SOGEMEE.getLog().getPrinc().getFabrication().dispose();
        }
            if(SOGEMEE.getLog().getPrinc().getApprovisionnement().isVisible()){
            SOGEMEE.getLog().getPrinc().getApprovisionnement().dispose();
        }
          
        SOGEMEE.getLog().getPrinc().getFabrication();
        SOGEMEE.getLog().getPrinc().getFabrication().setVisible(true);
            }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(SOGEMEE.getLog().getPrinc().getPerson().isVisible()){
            SOGEMEE.getLog().getPrinc().getPerson().dispose();
        }
        if(SOGEMEE.getLog().getPrinc().getVente().isVisible()){
            SOGEMEE.getLog().getPrinc().getVente().dispose();
        }
         if(SOGEMEE.getLog().getPrinc().getFabrication().isVisible()){
            SOGEMEE.getLog().getPrinc().getFabrication().dispose();
        }
            if(SOGEMEE.getLog().getPrinc().getApprovisionnement().isVisible()){
            SOGEMEE.getLog().getPrinc().getApprovisionnement().dispose();
        }
          
        SOGEMEE.getLog().getPrinc().getVente();
        SOGEMEE.getLog().getPrinc().getVente().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(SOGEMEE.getLog().getPrinc().getPerson().isVisible()){
            SOGEMEE.getLog().getPrinc().getPerson().dispose();
        }
        if(SOGEMEE.getLog().getPrinc().getVente().isVisible()){
            SOGEMEE.getLog().getPrinc().getVente().dispose();
        }
         if(SOGEMEE.getLog().getPrinc().getFabrication().isVisible()){
            SOGEMEE.getLog().getPrinc().getFabrication().dispose();
        }
            if(SOGEMEE.getLog().getPrinc().getApprovisionnement().isVisible()){
            SOGEMEE.getLog().getPrinc().getApprovisionnement().dispose();
        }
          
        SOGEMEE.getLog().getPrinc().getVente();
        SOGEMEE.getLog().getPrinc().getVente().setVisible(true);
        SOGEMEE.getLog().getPrinc().getVente().getjTabbedPane1().setSelectedIndex(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Guide().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
