/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sogemee;

import approvisionnement.Fen_Approvisionnement;
import fabrication.Fen_Fabrication;
import gesperson.Fen_Menu_GesPersonnel;
import java.awt.Dialog;
import java.awt.Image;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import sogemee.User.Fen_Utilisateurs;
import vente.Fen_FactureClient;
import vente.Menu_Vente;

/**
 *
 * @author el-diablo
 */
public class Principale extends javax.swing.JFrame {
    private Fen_Menu_GesPersonnel person;
    private Menu_Vente vente;
    private Guide gui;
    private Fen_Fabrication fabrication;
    private Fen_Approvisionnement approvisionnement;
    private Fen_FactureClient facture;
    private Fen_Utilisateurs users;
   String pp;
    /**
     * Creates new form Principale
     */
    public Principale() {
pp=SOGEMEE.user.getProfil().getLibelleProfil();
        initComponents();
 


    }

    public Fen_Approvisionnement getApprovisionnement() {
        return approvisionnement;
    }

    public Fen_Fabrication getFabrication() {
        return fabrication;
    }

    public Guide getGui() {
        return gui;
    }

    public Fen_Menu_GesPersonnel getPerson() {
        return person;
    }

    public Menu_Vente getVente() {
        return vente;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal Ges SOGEME");
        setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.foreground"));

        jPanel1.setBackground(new java.awt.Color(228, 255, 201));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 68, 68));
        jLabel1.setText("Gestion des activités de SOGEME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel1)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(104, 118, 178));

        jMenu1.setText("Fichier");

        jMenuItem2.setText("Configuration");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Quitter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu14.setText("Modularité");

        jMenuItem37.setText("Approvisionnement");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem37);

        jMenuItem38.setText("GRH");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem38);

        jMenuItem39.setText("Fabrication");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem39);

        jMenuItem40.setText("Vente");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem40);

        jMenuItem41.setText("Comptabilité");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem41);

        jMenuBar1.add(jMenu14);

        jMenu12.setText("Etats");

        jMenuItem4.setText("Actuel du stock");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem4);

        jMenuItem17.setText("Dustock à une date");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem17);

        jMenuItem24.setText("Des commandes clients");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem24);

        jMenuItem25.setText("Des commandes Fournisseurs");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem25);

        jMenuItem26.setText("CA annuel");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem26);

        jMenuItem27.setText("CA mensuel");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem27);

        jMenuItem28.setText("CA semestriel");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem28);

        jMenuItem29.setText("CA trimestriel");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem29);

        jMenuItem30.setText("Montant d'achat annuel par forme");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem30);

        jMenuItem31.setText("Montant d'achat mensuel par forme");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem31);

        jMenuItem32.setText("Montant d'achat trimestriel par forme");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem32);

        jMenuItem33.setText("Montant d'achat semestriel par forme");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem33);

        jMenuItem34.setText("Montant des achats faits par un client");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem34);

        jMenuItem35.setText("Montant d'achat auprès d'un fournisseur sur une période");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem35);

        jMenuItem36.setText("Montant des ventes de meuble par modèle");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem36);

        jMenuItem3.setText("Journal");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem3);

        jMenuItem5.setText("Grand Livre");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem5);

        jMenuBar1.add(jMenu12);

        jMenu13.setText("Utilisateur");

        jMenuItem18.setText("Ouvrir");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem18);

        jMenuBar1.add(jMenu13);
        if(pp.equals("Administrateur") ){
            jMenu13.setVisible(true);
        }
        else{
            jMenu13.setVisible(false);
        }

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
System.exit(-1);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        if(gui==null){
            gui=new Guide();
        }
        gui.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        try{
            Statement s=sogemee.SOGEMEE.c.getConn().createStatement();
            s.executeUpdate("drop view etatStock");
            s.close();
            Statement ses=sogemee.SOGEMEE.c.conn.createStatement();
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            Date date=new Date();
            String requete="create view etatStock as";
            requete+=" select p.idPlanche,t.libelleTypeBois,f.libelleFormePlanche,l.valeurLongeur,-sum(i.qteSortie) as qte from planche p,typeBois t,formePlanche f,longeurPlanche l,bonSortie_planche i,bonSortie b where p.suppr=0 and p.idTypeBois=t.idTypeBois and p.idFormePlanche=f.idFormePlanche and b.idBonSortie=i.idBonSortie and b.suppr=0 and p.idLongeurPlanche=l.idLongeurPlanche and i.idPlanche=p.idPlanche and dateBonSortie <='"+format.format(date) +"'  group by i.idPlanche";
            requete+=" union";
            requete+=" select p.idPlanche,t.libelleTypeBois,f.libelleFormePlanche,l.valeurLongeur,-sum(i.qteSortie) from planche p,typeBois t,formePlanche f,longeurPlanche l,sortie_planche i,sortie b where p.suppr=0 and p.idTypeBois=t.idTypeBois and p.idFormePlanche=f.idFormePlanche and b.idSortie=i.idSortie and p.idLongeurPlanche=l.idLongeurPlanche and i.idPlanche=p.idPlanche and dateSortie <='"+format.format(date) +"'  group by i.idPlanche";
            requete+=" union ";
            requete+=" select p.idPlanche,t.libelleTypeBois,f.libelleFormePlanche,l.valeurLongeur,sum(i.qteLivraison) from planche p,typeBois t,formePlanche f,longeurPlanche l,livraison_planche i,livraison k where p.idTypeBois=t.idTypeBois and p.idFormePlanche=f.idFormePlanche and p.idLongeurPlanche=l.idLongeurPlanche and k.idLivraison=i.idLivraison and i.idPlanche=p.idPlanche and dateLivraison<='"+format.format(date)+"' and k.suppr=0 group by i.idPlanche ";
            requete+=" union"; 
            requete+=" select"; 
            requete+=" p.idPlanche,t.libelleTypeBois,f.libelleFormePlanche,l.valeurLongeur,-sum(c.qteFacture) from planche p,typeBois t,formePlanche f,longeurPlanche l,factureClient i,concerner c where p.idTypeBois=t.idTypeBois and p.idFormePlanche=f.idFormePlanche and p.idLongeurPlanche=l.idLongeurPlanche and c.idFactureClient=i.idFactureClient and c.idPlanche=p.idPlanche and dateFacture<='"+format.format(date)+"'  and i.suppr=0 and c.typeAction='Vente' group by c.idPlanche";
            ses.executeUpdate(requete);      
      
            try {//JOptionPane.showMessageDialog(null,"wep");
            JasperDesign jasperdesign = JRXmlLoader.load("src/vente/etatStock.jrxml");

            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);

            
            Map param = new HashMap();
            //param.put("periode", forma.parse(p.getLibelle_periodepaie()));
            //param.put("agent",id);

            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
            

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
            
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed

        try{
            Statement s=sogemee.SOGEMEE.c.getConn().createStatement();
            Statement ses=sogemee.SOGEMEE.c.conn.createStatement();
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            String date=JOptionPane.showInputDialog(null,"Entrer la date au format aaaa-mm-jj");
            try{
                format.parse(date);
                Date d=new Date();
                if(format.parse(date).after(d)){
                    JOptionPane.showMessageDialog(null,"La date entrée esr supérieur à la date du jour");
                    return;
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"La date entrée n'est pas valide");
                return;
            }
            s.executeUpdate("drop view etatStock");
            s.close();
            String requete="create view etatStock as";
            requete+=" select p.idPlanche,t.libelleTypeBois,f.libelleFormePlanche,l.valeurLongeur,-sum(i.qteSortie) as qte from planche p,typeBois t,formePlanche f,longeurPlanche l,bonSortie_planche i,bonSortie b where p.suppr=0 and p.idTypeBois=t.idTypeBois and p.idFormePlanche=f.idFormePlanche and b.idBonSortie=i.idBonSortie and b.suppr=0 and p.idLongeurPlanche=l.idLongeurPlanche and i.idPlanche=p.idPlanche and dateBonSortie <='"+date +"'  group by i.idPlanche";
            requete+=" union ";
            requete+=" select p.idPlanche,t.libelleTypeBois,f.libelleFormePlanche,l.valeurLongeur,sum(i.qteLivraison) from planche p,typeBois t,formePlanche f,longeurPlanche l,livraison_planche i,livraison k where p.idTypeBois=t.idTypeBois and p.idFormePlanche=f.idFormePlanche and p.idLongeurPlanche=l.idLongeurPlanche and k.idLivraison=i.idLivraison and i.idPlanche=p.idPlanche and dateLivraison<='"+date+"' and k.suppr=0 group by i.idPlanche ";
            requete+=" union"; 
            requete+=" select"; 
            requete+=" p.idPlanche,t.libelleTypeBois,f.libelleFormePlanche,l.valeurLongeur,-sum(c.qteFacture) from planche p,typeBois t,formePlanche f,longeurPlanche l,factureClient i,concerner c where p.idTypeBois=t.idTypeBois and p.idFormePlanche=f.idFormePlanche and p.idLongeurPlanche=l.idLongeurPlanche and c.idFactureClient=i.idFactureClient and c.idPlanche=p.idPlanche and dateFacture<='"+date+"'  and i.suppr=0 and c.typeAction='Vente' group by c.idPlanche";
            ses.executeUpdate(requete);      
      
            try {//JOptionPane.showMessageDialog(null,"wep");
            JasperDesign jasperdesign = JRXmlLoader.load("src/vente/etatStock.jrxml");

            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);

            
            Map param = new HashMap();
            //param.put("periode", forma.parse(p.getLibelle_periodepaie()));
            //param.put("agent",id);

            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
            

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
            
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed

        if(users!=null){
        users.dispose();    
        }
        else{
            users=new Fen_Utilisateurs();
            users.setVisible(true);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
            try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/sogemee/etatCommandesClient.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
 try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/sogemee/etatCommandeFour.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
 try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/sogemee/CAannuel.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed

        String annee=JOptionPane.showInputDialog("Veuillez entrer l'année svp");
        try{
            Integer.parseInt(annee);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Année invalide");
            return;
        }
        try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/sogemee/CAmensuel.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
            param.put("annee", annee);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
String annee=JOptionPane.showInputDialog("Veuillez entrer l'année svp");
        try{
            Integer.parseInt(annee);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Année invalide");
            return;
        }
        try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/sogemee/CAsemestriel.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
            param.put("annee", annee);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            }         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
String annee=JOptionPane.showInputDialog("Veuillez entrer l'année svp");
        try{
            Integer.parseInt(annee);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Année invalide");
            return;
        }
        try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/sogemee/CAtrimestriel.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
            param.put("annee", annee);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed

        try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/sogemee/FPannuel.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
           
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            }          // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
String annee=JOptionPane.showInputDialog("Veuillez entrer l'année svp");
        try{
            Integer.parseInt(annee);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Année invalide");
            return;
        }
        try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/sogemee/FPmensuel.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
            param.put("annee", annee);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            }          // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
String annee=JOptionPane.showInputDialog("Veuillez entrer l'année svp");
        try{
            Integer.parseInt(annee);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Année invalide");
            return;
        }
        try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/sogemee/FPtrimestriel.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
            param.put("annee", annee);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
String annee=JOptionPane.showInputDialog("Veuillez entrer l'année svp");
        try{
            Integer.parseInt(annee);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Année invalide");
            return;
        }
        try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/sogemee/FPsemestriel.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
            param.put("annee", annee);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            }         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed

        EtatClient c=new EtatClient();
        c.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
EtatFournisseur f=new EtatFournisseur();
f.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed

        try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/gesperson/venteMeuble.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
           
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            }         
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
 if(person!=null){
            person.dispose();
        }
        if(vente!=null){
            vente.dispose();
        }
         if(fabrication!=null){
            fabrication.dispose();
        }
            if(approvisionnement!=null){
            approvisionnement.dispose();
        }        approvisionnement=new Fen_Approvisionnement();
        approvisionnement.setVisible(true);
        approvisionnement.setLocation(100,100);
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        if(person!=null){
            person.dispose();
        }
        if(vente!=null){
            vente.dispose();
        }
         if(fabrication!=null){
            fabrication.dispose();
        }
            if(approvisionnement!=null){
            approvisionnement.dispose();
        }
        person=new Fen_Menu_GesPersonnel();
        person.setLocation(100,100);
        person.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
 if(person!=null){
            person.dispose();
        }
        if(vente!=null){
            vente.dispose();
        }
         if(fabrication!=null){
            fabrication.dispose();
        }
            if(approvisionnement!=null){
            approvisionnement.dispose();
        }        fabrication=new Fen_Fabrication();
//        fabrication.getjTabbedPane1().setSelectedIndex(2);
        fabrication.setLocation(100,100);
        fabrication.setVisible(true);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
 if(person!=null){
            person.dispose();
        }
        if(vente!=null){
            vente.dispose();
        }
         if(fabrication!=null){
            fabrication.dispose();
        }
            if(approvisionnement!=null){
            approvisionnement.dispose();
        }       vente=new Menu_Vente();
 //       fabrication.getjTabbedPane1().setSelectedIndex(2);
        vente.setLocation(100,100);
        vente.setVisible(true);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
 if(person!=null){
            person.dispose();
        }
        if(vente!=null){
            vente.dispose();
        }
         if(fabrication!=null){
            fabrication.dispose();
        }
            if(approvisionnement!=null){
            approvisionnement.dispose();
        }        vente=new Menu_Vente();
//        vente.getjTabbedPane1().setSelectedIndex(1);
        vente.setLocation(100,100);
        vente.setVisible(true);            // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/vente/journal.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
 
            Date date=new Date();
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            param.put("date",format.format(date));
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            }          // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        try {
            JasperDesign jasperdesign = JRXmlLoader.load("src/vente/GrandLivre.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jasperdesign);
            Map param = new HashMap();
           
            JasperPrint jp = JasperFillManager.fillReport(jr, param, sogemee.SOGEMEE.c.getConn());
            JasperViewer.viewReport(jp,false);
           }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            }          // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principale().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
