/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sogemee.User;

import gesperson.Agent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author el-diablo
 */
public class Fen_Utilisateurs extends javax.swing.JFrame {

    private ArrayList profils=new ArrayList();
    private ArrayList agents =new ArrayList();
    private ArrayList utilisateurs=new ArrayList();
    /**
     * Creates new form Fen_Utilisateurs
     */
    public Fen_Utilisateurs() {
        initComponents();
        remplirUser();
        remplirNoms();
        remplirProfils();
    }
  
      public void remplirProfils(){
        DefaultComboBoxModel mod=new DefaultComboBoxModel();
        try {
            Statement s=sogemee.SOGEMEE.c.getConn().createStatement();
            ResultSet r=s.executeQuery("select idProfil,libelleProfil from profil ");
            while(r.next()){
                Profil p=new Profil(r.getInt(1),r.getString(2));
                profils.add(p);
                mod.addElement(r.getString(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Fen_Utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
        }
        profil.setModel(mod);
    }
    
    
    public void remplirNoms(){
        DefaultComboBoxModel mod=new DefaultComboBoxModel();
        try {
            Statement s=sogemee.SOGEMEE.c.getConn().createStatement();
            ResultSet r=s.executeQuery("select a.idAgent,a.nomAgent,a.prenomAgent from agent a where a.suppr=0 ");
            while(r.next()){
                Agent a=new Agent(r.getInt(1), r.getString(2),r.getString(3));
                agents.add(a);
                mod.addElement(r.getString(2)+" "+r.getString(3));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Fen_Utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
        }
        agent.setModel(mod);
    }
    
    public void remplirUser(){
        DefaultTableModel mod=new DefaultTableModel();
        mod.addColumn("Pseudo");
        mod.addColumn("Nom Agent");
        mod.addColumn("Prenom Agent");
        mod.addColumn("Profil");
        try {
            Statement s=sogemee.SOGEMEE.c.getConn().createStatement();
            ResultSet r=s.executeQuery("select a.idAgent,a.nomAgent,a.prenomAgent,u.idUtilisateur,u.login,u.password,p.idProfil,p.libelleProfil from agent a,utilisateur u,profil p where a.idAgent=u.idAgent and u.idProfil=p.idProfil and a.suppr=0 and u.suppr=0");
            while(r.next()){
                Agent a=new Agent(r.getInt(1), r.getString(2),r.getString(3));
                Profil p=new Profil(r.getInt(7), r.getString(8));
                Utilisateur u=new Utilisateur(r.getInt(4),r.getString(5),r.getString(6), a);
                u.setProfil(p);
                utilisateurs.add(u);
                Object [] ee={u.getLogin(),a.getNomAgent(),a.getPrenomAgent(),p.getLibelleProfil()};
                mod.addRow(ee);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Fen_Utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableUser.setModel(mod);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pseudo = new javax.swing.JTextField();
        motdepasse = new javax.swing.JPasswordField();
        BtnAdd = new javax.swing.JButton();
        BtnMod = new javax.swing.JButton();
        BtnSuppr = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        BtnAnn = new javax.swing.JButton();
        agent = new javax.swing.JComboBox();
        profil = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUser);

        jLabel1.setText("Utilisateurs");

        jLabel2.setText("Pseudo");

        jLabel3.setText("Agent");

        jLabel5.setText("Mot de passe");

        BtnAdd.setText("Ajouter");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnMod.setText("Modifier");
        BtnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModActionPerformed(evt);
            }
        });

        BtnSuppr.setText("Supprimer");
        BtnSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSupprActionPerformed(evt);
            }
        });

        BtnSave.setText("Enregistrer");
        BtnSave.setEnabled(false);
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnAnn.setText("Annuler");
        BtnAnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnnActionPerformed(evt);
            }
        });

        jLabel4.setText("Profil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnSave)
                                    .addComponent(BtnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnSuppr))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pseudo)
                                    .addComponent(motdepasse)
                                    .addComponent(agent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(profil, 0, 209, Short.MAX_VALUE)))
                            .addComponent(BtnAnn)))
                    .addComponent(jLabel1))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnAnn, BtnSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAdd))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(motdepasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSave))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(BtnMod)
                            .addComponent(agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSuppr)
                            .addComponent(profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(BtnAnn)))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserMouseClicked

        int ind=tableUser.getSelectedRow();
        Utilisateur u=(Utilisateur) utilisateurs.get(ind);
        agent.setSelectedItem(u.getAgent().getNomAgent()+" "+u.getAgent().getPrenomAgent());
        profil.setSelectedItem(u.getProfil().getLibelleProfil());
        pseudo.setText(u.getLogin());
        motdepasse.setText(u.getPassword());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tableUserMouseClicked

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed

        BtnAdd.setEnabled(false);
        BtnSave.setEnabled(true);
        BtnMod.setEnabled(false);
        BtnSuppr.setEnabled(false);
        motdepasse.setText(null);
        pseudo.setText(null);
        agent.setSelectedItem(0);
        profil.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed

        if(pseudo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Pseudo invalide");
            return;
        }
        char []mdp=motdepasse.getPassword();
        if(mdp.length<6){
            JOptionPane.showMessageDialog(null,"Mot de passe invalide. Six(6) caractères minimun");
            return;
        }
        String m =new String();
        for(int i=0;i<mdp.length;i++){
            m+=mdp[i];
        }
        for(int i=0;i<utilisateurs.size();i++){
            Utilisateur u=(Utilisateur) utilisateurs.get(i);
            if(u.getLogin().equals(pseudo.getText())){
                JOptionPane.showMessageDialog(null,"Ce pseudo est déjà utilisé");
                return;
            }
        }
        String pseu=pseudo.getText();
        
        Agent a=(Agent) agents.get(agent.getSelectedIndex());
        Profil prof=(Profil) profils.get(profil.getSelectedIndex());
        Utilisateur util=new Utilisateur(pseu,m);
        util.setProfil(prof);
        util.setAgent(a);
       // JOptionPane.showMessageDialog(null,a.getIdAgent()+" "+prof.getIdProfil()+" "+util.getLogin()+" "+util.getPassword());
        util.saveUser();
        remplirUser();
        remplirProfils();
        remplirNoms();
        BtnAdd.setEnabled(true);
        BtnSave.setEnabled(false);
        BtnMod.setEnabled(true);
        BtnSuppr.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModActionPerformed

        int ind=tableUser.getSelectedRow();
        if(pseudo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Pseudo invalide");
            return;
        }
        char []mdp=motdepasse.getPassword();
        if(mdp.length<6){
            JOptionPane.showMessageDialog(null,"Mot de passe invalide. Six(6) caractères minimun");
            return;
        }
        String m ="";
        for(int i=0;i<mdp.length;i++){
            m+=mdp[i];
        }
        for(int i=0;i<utilisateurs.size();i++){
            if(i!=ind){
            Utilisateur u=(Utilisateur) utilisateurs.get(i);
            if(u.getLogin().equals(pseudo.getText())){
                JOptionPane.showMessageDialog(null,"Ce pseudo est déjà utilisé");
                return;
               }    
            }
        }
         Utilisateur u=(Utilisateur) utilisateurs.get(ind);
         if(JOptionPane.showConfirmDialog(null,"Êtes vous sûres de modifier ce utilisateur?")==0){
         u.setLogin(pseudo.getText());
         Profil p=(Profil) profils.get(profil.getSelectedIndex());
         u.setProfil(p);
         u.setPassword(m);
         u.modifUser();
         remplirNoms();
         remplirProfils();
         remplirUser();    
         }
         
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModActionPerformed

    private void BtnSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSupprActionPerformed

        int ind=tableUser.getSelectedRow();
         Utilisateur u=(Utilisateur) utilisateurs.get(ind);
         if(JOptionPane.showConfirmDialog(null,"Êtes vous sûres de supprimer ce utilisateur?")==0){
         u.deleteUser();
         remplirNoms();
         remplirProfils();
         remplirUser();    
         }
         
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSupprActionPerformed

    private void BtnAnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnnActionPerformed

        BtnSave.setEnabled(false);
        BtnMod.setEnabled(true);
        BtnSuppr.setEnabled(true);
        BtnAdd.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_BtnAnnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fen_Utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fen_Utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fen_Utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fen_Utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Fen_Utilisateurs().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnAnn;
    private javax.swing.JButton BtnMod;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnSuppr;
    private javax.swing.JComboBox agent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField motdepasse;
    private javax.swing.JComboBox profil;
    private javax.swing.JTextField pseudo;
    private javax.swing.JTable tableUser;
    // End of variables declaration//GEN-END:variables
}
